# config.yml
model_type:
  netc
# mdoel args
model:        
  image_channel: 3
  image_weight: 512
  image_height: 512
  patch_size: 2
  embedding_dim: 40
  out_channel_m: 192
  out_channel_n: 128
  lamda: 0.013
  finetune_model_dir: "./saved_model/stf/0.013"  
  device: cuda   

# trainning args
traininng:
  batch_size: 2               
  epochs: 50      
  learning_rate: 0.0001   
  optimizer: Adam              
  weight_decay: 0.0001
  clip_max_norm: 0.5
  factor: 0.3
  patience: 15         
  device: cuda

dataset_type:
  compression
dataset:
  target_width: 512
  target_height: 512
  train_data_path: datasets/camvid/camvid_train/train.jsonl
  test_data_path: datasets/camvid/camvid_train/test.jsonl
  valid_data_path: datasets/camvid/camvid_train/val.jsonl

logging:
  eval_interval: 100           
  save_dir: "./saved_model/netc"   