# config.yml
model_type:
  eticn
# mdoel args
model:        
  image_channel: 3
  image_weight: 512
  image_height: 512
  patch_size: 2
  embedding_dim: 40
  window_size: 4
  head_num: 1
  shift_size: 0
  out_channel_m: 192
  out_channel_n: 128
  group_num: 64
  codebook_size: 512
  transfomer_head: 2
  transfomer_blocks: 3
  drop_prob: 0.1
  lamda: 0.013
  sigma: 0.0001
  beta: 0.0001
  finetune_model_dir: "./saved_model/eticn/0.18"  
  university_pretrain_path: camvid_64_512.npy
  device: cuda   

# trainning args
traininng:
  batch_size: 2               
  epochs: 100          
  learning_rate: 0.0001   
  optimizer: Adam              
  weight_decay: 0.0001
  clip_max_norm: 0.5
  factor: 0.3
  patience: 15         
  device: cuda

dataset_type:
  eticn
dataset:
  target_width: 512
  target_height: 512
  train_data_path: datasets/camvid/camvid_train/train.jsonl
  test_data_path: datasets/camvid/camvid_train/test.jsonl
  valid_data_path: datasets/camvid/camvid_train/val.jsonl



logging:
  eval_interval: 100           
  save_dir: "./saved_model/eticn"   